<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="com.mytime.testsuite.MyTimeTestSuite" tests="1" time="6.041" ignored="0" failures="1" timestamp="14 Aug 2018 12:40:52 GMT" skipped="0" hostname="DESKTOP-JOCTPOA" errors="0">
  <testcase name="testcase_001_myTimeApplication_LoginTest" time="6.041" classname="com.mytime.testsuite.MyTimeTestSuite">
    <failure type="java.lang.AssertionError" message="Expected condition is not met expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Expected condition is not met expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.mytime.applicationpages.WelcomePage.clickOnSignInWithGoogleButton(WelcomePage.java:28)
	at com.mytime.testsuite.MyTimeTestSuite.testcase_001_myTimeApplication_LoginTest(MyTimeTestSuite.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- testcase_001_myTimeApplication_LoginTest -->
</testsuite> <!-- com.mytime.testsuite.MyTimeTestSuite -->
